### PR TITLE
fix AnvilScreen with BCLIB, use lower priority

### LINKED ISSUE #11: Incompatibility with BCLib, Reforged button on anvil doesn't work
I'm trying to click on the reforge button in the anvil menu and it just doesn't work.

### PR DESCRIPTION
**Pull request by FederAndInk**
Fix #11

### CODE REVIEW

**Comment by Globox1997** [comment]
;) higher priority means a lower value not a higher one

**Comment by FederAndInk** [comment]
right, sorry, I'll rename the commit. but the value 1500 is correct right?

**Comment by Globox1997** [comment]
lower priority will get applied later if this is what you want

**Comment by FederAndInk** [comment]
thanks for the merge :)
would it be possible to have a release on curseforge for 1.18.2? 🙏

**Comment by itsdinkd** [comment]
Can we get a release for 1.18.2 please? Feder patched this mainly for AQM for using TieredZ which is 1.18.2

**Comment by Globox1997** [comment]
Released it on cf

**Pull request merged**
